# Netlify Configuration for AutoCam
# This file configures how Netlify builds and deploys the AutoCam application

[build]
  # Command to build the Next.js application
  command = "npm install && npm run build"

  # Directory containing the built application
  # Next.js outputs to .next directory
  publish = ".next"



# Build environment variables (these are used during build time)
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"
  # Omit select keys from secrets scan to avoid false positives
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_WS_URL,NEXT_PUBLIC_APP_URL,NODE_ENV,AI_WORKER_URL,JWT_SECRET"

# Environment variables for production
[env.production]
  # These should be set in Netlify dashboard
  # NEXT_PUBLIC_SUPABASE_URL = "your-supabase-url"
  # NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-anon-key"
  # DATABASE_URL = "your-database-url"
  # GOOGLE_CLIENT_ID = "your-google-client-id"
  # GOOGLE_CLIENT_SECRET = "your-google-client-secret"
  # AI_WORKER_URL = "your-modal-ai-worker-url"





# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Context-specific settings
[context.production]
  command = "npm install && npm run build"
  publish = ".next"

[context.deploy-preview]
  command = "npm install && npm run build"
  publish = ".next"

[context.branch-deploy]
  command = "npm install && npm run build"
  publish = ".next"



# Next.js on Netlify plugin (lets Netlify handle Next SSR/API routing correctly)
[[plugins]]
  package = "@netlify/plugin-nextjs"
